### ISSUE TITLE
how to run

### ISSUE THREAD

**Issue by kavehmollaei** [SupraAXES/SupraDaaS#1]
How to run supraDaas
![image](https://github.com/user-attachments/assets/fa40b229-e4b4-4d7e-a4a5-dc732ff6ad17)
how to resolve the problem?

when I create a vm I have this ERROR>>>>
vm-manager-1 | INFO:root:rpc_req: {'method': 'run_vm', 'id': 1732065543768, 'jsonrpc': '2.0', 'params': {'serv_name': 'dvm-99522383-9ada-4dad-8de3-e03e294811e4', 'vm_id': 'dvm-99522383-9ada-4dad-8de3-e03e294811e4', 'container_network': 'supra_projectors', 'serv_token': '99522383-9ada-4dad-8de3-e03e294811e4', 'vm_opts': {'guest_vnc': True, 'cores': '2', 'keep_report_quitting': False, 'guest_restrict': False, 'ram': '4G', 'tcp_ports': '("127.0.0.1:5985:5985")'}, 'os_type': 'ubuntu-2204', 'vm_id_type': 'machine'}}
vm-manager-1 | ERROR:jsonrpcserver.async_dispatcher:dvm-99522383-9ada-4dad-8de3-e03e294811e4 not found
vm-manager-1 | Traceback (most recent call last):
vm-manager-1 | File "/usr/local/lib/python3.11/dist-packages/jsonrpcserver/async_dispatcher.py", line 37, in call
vm-manager-1 | result = await method(
vm-manager-1 | ^^^^^^^^^^^^^
vm-manager-1 | File "/supra/bin/app.py", line 112, in run_vm
vm-manager-1 | storage_dir = machine_man.to_real_dir(vm_id)
vm-manager-1 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vm-manager-1 | File "/supra/bin/machine_man.py", line 36, in to_real_dir
vm-manager-1 | raise FileNotFoundError(f'{machine_id} not found')
vm-manager-1 | FileNotFoundError: dvm-99522383-9ada-4dad-8de3-e03e294811e4 not found
vm-manager-1 | INFO:root:rpc_resp: {'jsonrpc': '2.0', 'error': {'code': -32603, 'message': 'Internal error', 'data': 'dvm-99522383-9ada-4dad-8de3-e03e294811e4 not found'}, 'id': 1732065543768}
vm-manager-1 | INFO:aiohttp.access:127.0.0.1 [22/Nov/2024:04:34:43 +0000] "POST / HTTP/1.0" 200 318 "-" "Apache-HttpClient/4.5.14 (Java/17.0.12)"
vm-manager-1 | INFO:aiohttp.access:127.0.0.1 [22/Nov/2024:04:34:49 +0000] "POST / HTTP/1.0" 200 203 "-" "Python/3.11 aiohttp/3.10.10"
vm-manager-1 | INFO:root:rpc_req: {'method': 'list_template', 'id': 1732250100002, 'jsonrpc': '2.0', 'params': {}}
vm-manager-1 | INFO:root:rpc_resp: {'jsonrpc': '2.0', 'result': ['template-1', 'template-2'], 'id': 1732250100002}
vm-manager-1 | INFO:aiohttp.access:127.0.0.1 [22/Nov/2024:04:35:00 +0000] "POST / HTTP/1.0" 200 239 "-" "Apache-HttpClient/4.5.14 (Java/17.0.12)"
vm-manager-1 | INFO:aiohttp.access:127.0.0.1 [22/Nov/2024:04:35:19 +0000] "POST / HTTP/1.0" 200 203 "-" "Python/3.11 aiohttp/3.10.10"
supra-db-1 | 2024-11-22 04:35:43.698 UTC [27] LOG: checkpoint starting: time
supra-db-1 | 2024-11-22 04:35:44.232 UTC [27] LOG: checkpoint complete: wrote 6 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.509 s, sync=0.013 s, total=0.535 s; sync files=6, longest=0.012 s, average=0.003 s; distance=15 kB, estimate=15 kB; lsn=0/19957D0, redo lsn=0/1995778
vm-manager-1 | INFO:aiohttp.access:127.0.0.1 [22/Nov/2024:04:35:50 +0000] "POST / HTTP/1.0" 200 203 "-" "Python/3.11 aiohttp/3.10.10"
vm-manager-1 | INFO:aiohttp.access:127.0.0.1 [22/Nov/2024:04:36:20 +0000] "POST / HTTP/1.0" 200 203 "-" "Python/3.11 aiohttp/3.10.10"
<<<<

**Comment by kavehmollaei** [comment]
when I create a vm I have this ERROR>>>>
vm-manager-1   | INFO:root:rpc_req: {'method': 'run_vm', 'id': 1732065543768, 'jsonrpc': '2.0', 'params': {'serv_name': 'dvm-99522383-9ada-4dad-8de3-e03e294811e4', 'vm_id': 'dvm-99522383-9ada-4dad-8de3-e03e294811e4', 'container_network': 'supra_projectors', 'serv_token': '99522383-9ada-4dad-8de3-e03e294811e4', 'vm_opts': {'guest_vnc': True, 'cores': '2', 'keep_report_quitting': False, 'guest_restrict': False, 'ram': '4G', 'tcp_ports': '("127.0.0.1:5985:5985")'}, 'os_type': 'ubuntu-2204', 'vm_id_type': 'machine'}}
vm-manager-1   | ERROR:jsonrpcserver.async_dispatcher:dvm-99522383-9ada-4dad-8de3-e03e294811e4 not found
vm-manager-1   | Traceback (most recent call last):
vm-manager-1   |   File "/usr/local/lib/python3.11/dist-packages/jsonrpcserver/async_dispatcher.py", line 37, in call
vm-manager-1   |     result = await method(
vm-manager-1   |              ^^^^^^^^^^^^^
vm-manager-1   |   File "/supra/bin/app.py", line 112, in run_vm
vm-manager-1   |     storage_dir = machine_man.to_real_dir(vm_id)
vm-manager-1   |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vm-manager-1   |   File "/supra/bin/machine_man.py", line 36, in to_real_dir
vm-manager-1   |     raise FileNotFoundError(f'{machine_id} not found')
vm-manager-1   | FileNotFoundError: dvm-99522383-9ada-4dad-8de3-e03e294811e4 not found
vm-manager-1   | INFO:root:rpc_resp: {'jsonrpc': '2.0', 'error': {'code': -32603, 'message': 'Internal error', 'data': 'dvm-99522383-9ada-4dad-8de3-e03e294811e4 not found'}, 'id': 1732065543768}
vm-manager-1   | INFO:aiohttp.access:127.0.0.1 [22/Nov/2024:04:34:43 +0000] "POST / HTTP/1.0" 200 318 "-" "Apache-HttpClient/4.5.14 (Java/17.0.12)"
vm-manager-1   | INFO:aiohttp.access:127.0.0.1 [22/Nov/2024:04:34:49 +0000] "POST / HTTP/1.0" 200 203 "-" "Python/3.11 aiohttp/3.10.10"
vm-manager-1   | INFO:root:rpc_req: {'method': 'list_template', 'id': 1732250100002, 'jsonrpc': '2.0', 'params': {}}
vm-manager-1   | INFO:root:rpc_resp: {'jsonrpc': '2.0', 'result': ['template-1', 'template-2'], 'id': 1732250100002}
vm-manager-1   | INFO:aiohttp.access:127.0.0.1 [22/Nov/2024:04:35:00 +0000] "POST / HTTP/1.0" 200 239 "-" "Apache-HttpClient/4.5.14 (Java/17.0.12)"
vm-manager-1   | INFO:aiohttp.access:127.0.0.1 [22/Nov/2024:04:35:19 +0000] "POST / HTTP/1.0" 200 203 "-" "Python/3.11 aiohttp/3.10.10"
supra-db-1     | 2024-11-22 04:35:43.698 UTC [27] LOG:  checkpoint starting: time
supra-db-1     | 2024-11-22 04:35:44.232 UTC [27] LOG:  checkpoint complete: wrote 6 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.509 s, sync=0.013 s, total=0.535 s; sync files=6, longest=0.012 s, average=0.003 s; distance=15 kB, estimate=15 kB; lsn=0/19957D0, redo lsn=0/1995778
vm-manager-1   | INFO:aiohttp.access:127.0.0.1 [22/Nov/2024:04:35:50 +0000] "POST / HTTP/1.0" 200 203 "-" "Python/3.11 aiohttp/3.10.10"
vm-manager-1   | INFO:aiohttp.access:127.0.0.1 [22/Nov/2024:04:36:20 +0000] "POST / HTTP/1.0" 200 203 "-" "Python/3.11 aiohttp/3.10.10"
<<<<

**Comment by yy8402** [comment]
> vm-manager-1 | ERROR:jsonrpcserver.async_dispatcher:dvm-99522383-9ada-4dad-8de3-e03e294811e4 not found

The vm image was not there, do you have a template image in place?

Could you share what is in /opt/supra/daas/logs/app.log?

**Comment by kavehmollaei** [comment]
I have template image in place
![image](https://github.com/user-attachments/assets/ade3799d-861b-4062-bc3e-79b53e3e4b83)


![image](https://github.com/user-attachments/assets/b0b1004a-e648-44c5-9510-84aecab14907)

**Comment by yy8402** [comment]
> I have template image in place ![image](https://private-user-images.githubusercontent.com/35415391/397964849-ade3799d-861b-4062-bc3e-79b53e3e4b83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5MTgwODcsIm5iZiI6MTczNDkxNzc4NywicGF0aCI6Ii8zNTQxNTM5MS8zOTc5NjQ4NDktYWRlMzc5OWQtODYxYi00MDYyLWJjM2UtNzliNTNlM2U0YjgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDAxMzYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViNTg0ZGZjNDM1NTFlMTJhZGJlNDhiZThjZDYzZjgyMTM4YmEwM2Q5NjY5Yzg4Y2FiMjQ3MzIzNjdlZDhlZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RO0NUkhLCy-yNAGxozjSZYNnogMZEKUUr9Xemz5Jshw)
> 
> ![image](https://private-user-images.githubusercontent.com/35415391/397964784-b0b1004a-e648-44c5-9510-84aecab14907.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5MTgwODcsIm5iZiI6MTczNDkxNzc4NywicGF0aCI6Ii8zNTQxNTM5MS8zOTc5NjQ3ODQtYjBiMTAwNGEtZTY0OC00NGM1LTk1MTAtODRhZWNhYjE0OTA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDAxMzYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4NGY3ZGY1MDFlNjc1ODRhYmVhY2U1MWY1YjRlYjQ2ZjFkYWY4ZDQ5NzFhYWUyMzM3MDM2MmE5ZWZlOTFlYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1ZZTadVrxbITmORAY85zCvJiaAfgrfxheG0TYqhzsA4)

It seems you were trying to use the Win11 template image with management interface enabled. 
Could you share your info.json file? 
To enable management interface, [winrm for remote management](https://learn.microsoft.com/en-us/windows/win32/winrm/installation-and-configuration-for-windows-remote-management) should be enabled in the image and the info.json file should be set accordingly.

**Comment by kavehmollaei** [comment]
{
  "name": "Windows11-adm",
  "osType": "windows-11",
  "diskSize": "80G",
  "access": [{"protocol": "rdp", "port": "3389"}],
  "management": { "protocol": "rdp", "port": "5985", "interval": 10},
  "userMgr": 1,
  "adminName": "supra",
  "adminPasswd": "supra",
  "users": [{"user": "supra", "pass": "supra"}]
}
I enable winrm in my image

**Comment by yy8402** [comment]
> { "name": "Windows11-adm", "osType": "windows-11", "diskSize": "80G", "access": [{"protocol": "rdp", "port": "3389"}], "management": { "protocol": "rdp", "port": "5985", "interval": 10}, "userMgr": 1, "adminName": "supra", "adminPasswd": "supra", "users": [{"user": "supra", "pass": "supra"}] } I enable winrm in my image

Can you try template with management disabled at first?
{
  "name": "Windows11-noadmin",
  "osType": "windows-11",
  "diskSize": "80G"
}

**Comment by kavehmollaei** [comment]
yes I remove it
but I have problem yet
![Uploading 4.png…]()

**Comment by kavehmollaei** [comment]
![2](https://github.com/user-attachments/assets/aa8d6a0a-4520-41e0-9884-e2462d37d9d2)
![1](https://github.com/user-attachments/assets/2b646c5b-f374-4034-a9d0-40114b9b574f)
![3](https://github.com/user-attachments/assets/b62ad350-1f2f-406f-b0fe-4d7303c05bd2)
![4](https://github.com/user-attachments/assets/ff0d4f05-b615-44f9-af62-fe0880443c98)

**Comment by kavehmollaei** [comment]
please give me a video for config a windows 11

**Comment by yy8402** [comment]
> please give me a video for config a windows 11

sorry that I do not have a windows 11 image at the point. 

per your screenshots: 1. you already had a containered vm running; 2. the system tried to start another containered vm with the same name, and failed; 3. there was no valid vm set for users.

I have no idea how the system got into such situation, could you help to try:
1. remove all running vms
```shell
sudo docker rm dvm-**** --force
```  
2. delete all vms on the admin UI page

3.  remove all vm images in /opt/supra/daas/vm/storage/machine/
```shell
 sudo rm /opt/supra/daas/vm/storage/machine/*
```  
4. create a vm on the admin UI page, only add "Virtual Terminal" for "Access Method".
<img width="737" alt="Screen Shot 2024-12-26 at 13 56 45" src="https://github.com/user-attachments/assets/cb8eea7f-f55b-4803-8c9e-534973ac05cc" />

5. check whether the vm is presented on resource UI page. If yes, try to click the icon.

6. check /opt/supra/daas/logs/app.log

7. check vm-manager log

```shell
 sudo docker logs supradaas-vm-manager-1
```

**Comment by kavehmollaei** [comment]
[app.log](https://github.com/user-attachments/files/18264988/app.log)

 not work !!!
can you give me a video ?

**Comment by yy8402** [comment]
> [app.log](https://github.com/user-attachments/files/18264988/app.log)
> 
> not work !!! can you give me a video ?

Sure, here you go~
https://youtu.be/01CfMnsM_hA
